sudo: false
dist: xenial
language: php

services:
  - mysql
  - postgresql

php:
  - 7.4
  - 7.1

env:
  - DB=mysql
  - DB=pgsql

matrix:
  fast_finish: true

before_script:
  - git clone -b 2020.10 https://github.com/aimeos/aimeos-core core
  - cd core
  - curl -o composer https://getcomposer.org/composer-1.phar
  - php composer req --no-update aimeos/ai-controller-frontend:2020.10.x-dev aimeos/ai-controller-jobs:2020.10.x-dev
  - php composer req --no-update aimeos/ai-admin-jqadm:2020.10.x-dev aimeos/ai-admin-jsonadm:2020.10.x-dev
  - php composer req --no-update aimeos/ai-client-html:2020.10.x-dev aimeos/ai-client-jsonapi:2020.10.x-dev
  - php composer req --no-update aimeos/ai-laravel:2020.10.x-dev aimeos/ai-fosuser:2020.10.x-dev aimeos/ai-typo3:2020.10.x-dev
  - php composer req --no-update aimeos/ai-symfony:2020.10.x-dev aimeos/ai-swiftmailer:2020.10.x-dev aimeos/ai-twig:2020.10.x-dev
  - php composer req --no-update aimeos/ai-cache:2020.10.x-dev aimeos/ai-gettext:2020.10.x-dev aimeos/ai-monolog:2020.10.x-dev
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then composer req --no-update typo3/cms-core aimeos/ai-typo3:2020.10.x-dev; fi
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry php composer update
  - if [[ $DB = 'mysql' ]]; then mysql -e "CREATE DATABASE aimeos; GRANT ALL ON aimeos.* TO 'aimeos'@'127.0.0.1' IDENTIFIED BY 'aimeos'"; fi
  - if [[ $DB = 'mysql' ]]; then echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET SESSIOn sort_buffer_size=2097144; SET NAMES 'utf8'; SET SESSION sql_mode='ANSI'\" ) ), 'fs' => array( 'adapter' => 'Standard', 'basedir' => '.' ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c "CREATE DATABASE aimeos;" -U postgres; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c "CREATE USER aimeos PASSWORD 'aimeos';" -U postgres; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c "GRANT ALL PRIVILEGES ON DATABASE aimeos TO aimeos;" -U postgres; fi
  - if [[ $DB = 'pgsql' ]]; then echo "<?php return array( 'db' => array( 'adapter' => 'pgsql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array() ), 'fs' => array( 'adapter' => 'Standard', 'basedir' => '.' ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php; fi

script: "vendor/bin/phing setup test"
