sudo: false
dist: xenial
language: php

services:
  - mysql
  - postgresql

php:
  - 7.3
  - 7.1

env:
  - DB=mysql
  - DB=pgsql

matrix:
  fast_finish: true

before_script:
  - git clone https://github.com/aimeos/aimeos-core core
  - cd core
  - composer req --no-update aimeos/ai-controller-frontend:dev-master aimeos/ai-controller-jobs:dev-master
  - composer req --no-update aimeos/ai-admin-jqadm:dev-master aimeos/ai-admin-jsonadm:dev-master
  - composer req --no-update aimeos/ai-client-html:dev-master aimeos/ai-client-jsonapi:dev-master
  - composer req --no-update aimeos/ai-ezpublish:dev-master aimeos/ai-laravel:dev-master aimeos/ai-fosuser:dev-master
  - composer req --no-update aimeos/ai-slim:dev-master aimeos/ai-symfony:dev-master aimeos/ai-typo3:dev-master
  - composer req --no-update aimeos/ai-cache:dev-master aimeos/ai-gettext:dev-master aimeos/ai-monolog:dev-master
  - composer req --no-update aimeos/ai-swiftmailer:dev-master aimeos/ai-twig:dev-master
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update
  - if [[ $DB = 'mysql' ]]; then mysql -e "CREATE DATABASE aimeos; GRANT ALL ON aimeos.* TO 'aimeos'@'127.0.0.1' IDENTIFIED BY 'aimeos'"; fi
  - if [[ $DB = 'mysql' ]]; then echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET SESSIOn sort_buffer_size=2097144; SET NAMES 'utf8'; SET SESSION sql_mode='ANSI'\" ) ), 'fs' => array( 'adapter' => 'Standard', 'basedir' => '.' ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c "CREATE DATABASE aimeos;" -U postgres; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c "CREATE USER aimeos PASSWORD 'aimeos';" -U postgres; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c "GRANT ALL PRIVILEGES ON DATABASE aimeos TO aimeos;" -U postgres; fi
  - if [[ $DB = 'pgsql' ]]; then echo "<?php return array( 'db' => array( 'adapter' => 'pgsql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array() ), 'fs' => array( 'adapter' => 'Standard', 'basedir' => '.' ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php; fi

script: "vendor/bin/phing setup test"
